// SkiFree Terrain List
// Input File Date: 2021-04-04 23:18:35

// A good terrain has the following qualities:
// - doesn't have a bunch of flat ground, even if it's right outside the mission bounds (high octane)
// - is not fucking gigantic (stripmine, a bunch of other TR2 terrains)
// - doesn't have a bunch of steep plateaus
// - is not Magnum (a map where the fastest route is to discjump off a bunch of flat ridges)
// use $TerrainTest to test a terrain locally

%i = -1; // %i++ is pre-increment for some reason; it's -1 so it can start at 0
%j = -1; // %j++ is pre-increment for some reason; it's -1 so it can start at 0
%k = -1; // %k++ is pre-increment for some reason; it's -1 so it can start at 0

// ACCEPTED TERRAINS (82)
$SkiFreeTerrainList[%i++] = "Alcatraz.ter"; // yeah. seems fine
$SkiFreeTerrainList[%i++] = "Attrition.ter";
$SkiFreeTerrainList[%i++] = "BastardForge.ter";
$SkiFreeTerrainList[%i++] = "Broadside_nef.ter";
$SkiFreeTerrainList[%i++] = "Caldera.ter";
$SkiFreeTerrainList[%i++] = "Cardiac.ter";
$SkiFreeTerrainList[%i++] = "CCD.ter";
$SkiFreeTerrainList[%i++] = "CeleritySE.ter"; // I was on the fence on this one
$SkiFreeTerrainList[%i++] = "Cinerarium.ter";
$SkiFreeTerrainList[%i++] = "Coppera.ter"; // this seems fine. just gotta keep jumping over the mesas? plateaus? fjordr? Whatever
$SkiFreeTerrainList[%i++] = "DangerousCrossing_nef.ter"; // this level is fine
$SkiFreeTerrainList[%i++] = "DeathBirdsFly.ter";
$SkiFreeTerrainList[%i++] = "DesertofDeath_nef.ter";
$SkiFreeTerrainList[%i++] = "Embers.ter";
$SkiFreeTerrainList[%i++] = "Euro4_Bleed.ter";
$SkiFreeTerrainList[%i++] = "Euro4_Dissention.ter";
$SkiFreeTerrainList[%i++] = "Euro4_FrozenHope.ter"; // seems fine?
$SkiFreeTerrainList[%i++] = "Gorgon.ter";
$SkiFreeTerrainList[%i++] = "Hildebrand.ter";
$SkiFreeTerrainList[%i++] = "icedagger.ter";
$SkiFreeTerrainList[%i++] = "jaggedclaw.ter";
$SkiFreeTerrainList[%i++] = "LavaGods.ter"; // this is fine
$SkiFreeTerrainList[%i++] = "Magellan.ter";
$SkiFreeTerrainList[%i++] = "Magmatic.ter"; // a bit on the hard side
$SkiFreeTerrainList[%i++] = "Oasis.ter";
$SkiFreeTerrainList[%i++] = "Ocular.ter";
$SkiFreeTerrainList[%i++] = "PlanetX2.ter";
$SkiFreeTerrainList[%i++] = "Raindance_nef.ter";
$SkiFreeTerrainList[%i++] = "RandomTer1.ter";
$SkiFreeTerrainList[%i++] = "RandomTer10.ter";
$SkiFreeTerrainList[%i++] = "RandomTer2.ter";
$SkiFreeTerrainList[%i++] = "RandomTer4.ter";
$SkiFreeTerrainList[%i++] = "RandomTer5.ter";
$SkiFreeTerrainList[%i++] = "RandomTer6.ter";
$SkiFreeTerrainList[%i++] = "RandomTer7.ter";
$SkiFreeTerrainList[%i++] = "RandomTer8.ter";
$SkiFreeTerrainList[%i++] = "RandomTer9.ter"; // this canyon works somehow
$SkiFreeTerrainList[%i++] = "Respite.ter";
$SkiFreeTerrainList[%i++] = "Rollercoaster_nef.ter"; // unlike most canyon maps this actually turns out to be skiiable
$SkiFreeTerrainList[%i++] = "rst_Astro.ter";
$SkiFreeTerrainList[%i++] = "rst_bittergorge.ter";
$SkiFreeTerrainList[%i++] = "rst_crumpie.ter";
$SkiFreeTerrainList[%i++] = "rst_FaceCrossing.ter";
$SkiFreeTerrainList[%i++] = "Rst_ScorchedEarth.ter"; // it's fine
$SkiFreeTerrainList[%i++] = "rst_spit.ter"; // i got to gate 5 on a discless discjump launch run
$SkiFreeTerrainList[%i++] = "Rush.ter";
$SkiFreeTerrainList[%i++] = "S5_Centaur.ter";
$SkiFreeTerrainList[%i++] = "S5_Drache.ter";
$SkiFreeTerrainList[%i++] = "S5_Icedance.ter";
$SkiFreeTerrainList[%i++] = "S5_massive.ter"; // this is fine? I remember writing about deadstops but I don't see any?
$SkiFreeTerrainList[%i++] = "S5_Mordacity.ter";
$SkiFreeTerrainList[%i++] = "S5_rst_misadventure.ter";
$SkiFreeTerrainList[%i++] = "S5_Sherman.ter";
$SkiFreeTerrainList[%i++] = "S8_rst_dogma.ter";
$SkiFreeTerrainList[%i++] = "S8_rst_opus.ter";
$SkiFreeTerrainList[%i++] = "Sandstorm.ter";
$SkiFreeTerrainList[%i++] = "SkinnyDip.ter"; // really wanted to use one of the TR2 maps. This has a big scale but also nice hills
$SkiFreeTerrainList[%i++] = "SpinCycle.ter"; // this was borderline rejected
$SkiFreeTerrainList[%i++] = "StarFallCTF2.ter";
$SkiFreeTerrainList[%i++] = "Starfallen.ter";
$SkiFreeTerrainList[%i++] = "TL_Drorck.ter";
$SkiFreeTerrainList[%i++] = "TL_RoughLand.ter"; // this is kinda a finicky terrain but it works
$SkiFreeTerrainList[%i++] = "Tombstone.ter";
$SkiFreeTerrainList[%i++] = "TWL-BeachBlitz.ter";
$SkiFreeTerrainList[%i++] = "TWL-Boss.ter"; // this level is acceptable
$SkiFreeTerrainList[%i++] = "TWL-Cinereous.ter";
$SkiFreeTerrainList[%i++] = "TWL-Damnation.ter";
$SkiFreeTerrainList[%i++] = "TWL-Deserted.ter";
$SkiFreeTerrainList[%i++] = "TWL-Frozen.ter";
$SkiFreeTerrainList[%i++] = "TWL-Harvester.ter"; // why did I take this one
$SkiFreeTerrainList[%i++] = "TWL-Os_Iris.ter";
$SkiFreeTerrainList[%i++] = "TWL-Pandemonium.ter";
$SkiFreeTerrainList[%i++] = "TWL-WilderZone.ter";
$SkiFreeTerrainList[%i++] = "TWL-WoodyMyrk.ter";
$SkiFreeTerrainList[%i++] = "TWL2_Crevice.ter";
$SkiFreeTerrainList[%i++] = "TWL2_Frozenglory.ter";
$SkiFreeTerrainList[%i++] = "Wasteland.ter"; // whatever sure
$SkiFreeTerrainList[%i++] = "WoodyMyrkSE.ter";
$SkiFreeTerrainList[%i++] = "Xtra_Bastage.ter";
$SkiFreeTerrainList[%i++] = "Xtra_SoupLadle.ter";
$SkiFreeTerrainList[%i++] = "Xtra_ThunderGiant.ter"; // this map is garbage but it's fun to try to ski on it
$SkiFreeTerrainList[%i++] = "Xtra_VanDamned.ter";

// SUPERHARD (APRIL FOOLS) (6)
$SkiFreeTerrainListSuperHard[%j++] = "Confusco.ter"; // WAY too big.
$SkiFreeTerrainListSuperHard[%j++] = "FrozenFury.ter"; // even the parts inside mission bounds are unskiiable garbage
$SkiFreeTerrainListSuperHard[%j++] = "Hillside.ter"; // accepted into april fools set (though it really shouldn’t be – too many deadstops)
$SkiFreeTerrainListSuperHard[%j++] = "TL_Skylight.ter";
$SkiFreeTerrainListSuperHard[%j++] = "TWL-Katabatic.ter"; // oob still bad. this was accepted into april fools because you always need a katabatic joke somewhere
$SkiFreeTerrainListSuperHard[%j++] = "Xtra_Stripmine.ter";

// REJECTED FOR DEADSTOPS (61)
$SkiFreeTerrainListRejected[%k++] = "Abominable.ter";
$SkiFreeTerrainListRejected[%k++] = "AcidRain.ter";
$SkiFreeTerrainListRejected[%k++] = "AgentsOfFortune.ter";
$SkiFreeTerrainListRejected[%k++] = "AshesToAshes.ter";
$SkiFreeTerrainListRejected[%k++] = "Casern_Cavite.ter";
$SkiFreeTerrainListRejected[%k++] = "DustToDust.ter";
$SkiFreeTerrainListRejected[%k++] = "Equinox.ter";
$SkiFreeTerrainListRejected[%k++] = "Extra_Badlands1.ter";
$SkiFreeTerrainListRejected[%k++] = "Firestorm.ter";
$SkiFreeTerrainListRejected[%k++] = "Flashpoint.ter";
$SkiFreeTerrainListRejected[%k++] = "Fracas.ter";
$SkiFreeTerrainListRejected[%k++] = "Gauntlet.ter";
$SkiFreeTerrainListRejected[%k++] = "Gehenna.ter";
$SkiFreeTerrainListRejected[%k++] = "Haven.ter";
$SkiFreeTerrainListRejected[%k++] = "HO_Badlands.ter";
$SkiFreeTerrainListRejected[%k++] = "HO_Desert.ter";
$SkiFreeTerrainListRejected[%k++] = "HO_Ice.ter";
$SkiFreeTerrainListRejected[%k++] = "HO_Lush.ter";
$SkiFreeTerrainListRejected[%k++] = "IceBound.ter";
$SkiFreeTerrainListRejected[%k++] = "Invictus.ter";
$SkiFreeTerrainListRejected[%k++] = "MapAssets.ter";
$SkiFreeTerrainListRejected[%k++] = "Masada.ter"; // tiny dicked map
$SkiFreeTerrainListRejected[%k++] = "mmd.ter";
$SkiFreeTerrainListRejected[%k++] = "MoonDance2.ter"; // too many deadstop splotches
$SkiFreeTerrainListRejected[%k++] = "Octane.ter";
$SkiFreeTerrainListRejected[%k++] = "Overreach.ter";
$SkiFreeTerrainListRejected[%k++] = "PhasmaDust.ter";
$SkiFreeTerrainListRejected[%k++] = "Pyroclasm.ter";
$SkiFreeTerrainListRejected[%k++] = "Quagmire.ter";
$SkiFreeTerrainListRejected[%k++] = "Recalescence.ter";
$SkiFreeTerrainListRejected[%k++] = "Reversion.ter";
$SkiFreeTerrainListRejected[%k++] = "RiverDance.ter";
$SkiFreeTerrainListRejected[%k++] = "rst_isledebatalla.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Badlands.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Desert.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Ice.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Lush.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Night.ter";
$SkiFreeTerrainListRejected[%k++] = "SC_Normal.ter";
$SkiFreeTerrainListRejected[%k++] = "Scarabrae_nef.ter";
$SkiFreeTerrainListRejected[%k++] = "Sirocco.ter";
$SkiFreeTerrainListRejected[%k++] = "SolsDescent.ter";
$SkiFreeTerrainListRejected[%k++] = "SunDried.ter";
$SkiFreeTerrainListRejected[%k++] = "ThinIce.ter";
$SkiFreeTerrainListRejected[%k++] = "TL_MuddySwamp.ter";
$SkiFreeTerrainListRejected[%k++] = "Training1.ter";
$SkiFreeTerrainListRejected[%k++] = "Training2.ter";
$SkiFreeTerrainListRejected[%k++] = "Training3.ter";
$SkiFreeTerrainListRejected[%k++] = "Training4.ter";
$SkiFreeTerrainListRejected[%k++] = "TreasureIsland.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL_Crossfire.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-BaNsHee.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Curtilage.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Horde.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Neve.ter"; // it's trace amounts but they're in places you would probably do routes
$SkiFreeTerrainListRejected[%k++] = "TWL-NoShelter.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Slapdash.ter"; // crapdash
$SkiFreeTerrainListRejected[%k++] = "TWL2_Ruined.ter"; // looks like a decent terrain but isn’t
$SkiFreeTerrainListRejected[%k++] = "Tyre.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_StarFall_T1.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_ziggurat.ter";

// REJECTED FOR BEING UNSKIIABLE (57)
$SkiFreeTerrainListRejected[%k++] = "Archipelago.ter";
$SkiFreeTerrainListRejected[%k++] = "Bunkered.ter";
$SkiFreeTerrainListRejected[%k++] = "cloak.ter"; // the terrain is just too big for a fun race
$SkiFreeTerrainListRejected[%k++] = "CompUSA_Melee.ter"; // the hill is causing too much grief and the rest of the map doesn’t have enough value to justify it
$SkiFreeTerrainListRejected[%k++] = "Crater71.ter"; // this almost always generates something very unfun
$SkiFreeTerrainListRejected[%k++] = "DBS_Smoothed.ter";
$SkiFreeTerrainListRejected[%k++] = "EB_Hades.ter"; // not only is it extreme but you kinda have trouble reading the terrain too
$SkiFreeTerrainListRejected[%k++] = "Escalade.ter";
$SkiFreeTerrainListRejected[%k++] = "Euro_Drifts_SE.ter";
$SkiFreeTerrainListRejected[%k++] = "Geothermal.ter"; // spawn is usually on the plateau. It can generate good starts and bad starts but it's usually a mess
$SkiFreeTerrainListRejected[%k++] = "GodsRift.ter";
$SkiFreeTerrainListRejected[%k++] = "HillKing.ter";
$SkiFreeTerrainListRejected[%k++] = "Hoth.ter"; // why would you name a terrain hoth if it isn't snowy
$SkiFreeTerrainListRejected[%k++] = "IceGiant.ter"; // terrain is kinda extreme
$SkiFreeTerrainListRejected[%k++] = "IceRidge_nef.ter"; // canyons are just bad for this
$SkiFreeTerrainListRejected[%k++] = "Insalubria.ter";
$SkiFreeTerrainListRejected[%k++] = "JacobsLadder.ter"; // hills are WAY too extreme
$SkiFreeTerrainListRejected[%k++] = "Minotaur.ter";
$SkiFreeTerrainListRejected[%k++] = "mountking.ter";
$SkiFreeTerrainListRejected[%k++] = "norty.ter"; // too extreme
$SkiFreeTerrainListRejected[%k++] = "Pariah.ter"; // these hills are too fucking steep
$SkiFreeTerrainListRejected[%k++] = "Pariah2.ter"; // ditto
$SkiFreeTerrainListRejected[%k++] = "PuliVeivari.ter";
$SkiFreeTerrainListRejected[%k++] = "RandomTer3.ter"; // canyon fractal
$SkiFreeTerrainListRejected[%k++] = "Rasp.ter";
$SkiFreeTerrainListRejected[%k++] = "RavineV.ter";
$SkiFreeTerrainListRejected[%k++] = "Rimehold.ter";
$SkiFreeTerrainListRejected[%k++] = "rst_SimpleFlagArena.ter"; // literally squares
$SkiFreeTerrainListRejected[%k++] = "S5_rst_hawkingheat.ter";
$SkiFreeTerrainListRejected[%k++] = "S5_rst_reynard.ter"; // this map is pushing the bounds of variance
$SkiFreeTerrainListRejected[%k++] = "S5_rst_silenus.ter";
$SkiFreeTerrainListRejected[%k++] = "S8_zilch.ter";
$SkiFreeTerrainListRejected[%k++] = "Sanctuary.ter";
$SkiFreeTerrainListRejected[%k++] = "ShockRidge.ter"; // not a fan of these canyon levels
$SkiFreeTerrainListRejected[%k++] = "Snowblind_nef.ter"; // already knew this is a bad idea before I even started
$SkiFreeTerrainListRejected[%k++] = "Stonehenge_nef.ter"; // kryand tried to tell me this was a skiiable terrain. so I put the flags in different places. he no longer believes it's a skiiable terrain
$SkiFreeTerrainListRejected[%k++] = "Surreal.ter";
$SkiFreeTerrainListRejected[%k++] = "Talus.ter";
$SkiFreeTerrainListRejected[%k++] = "Titan.ter"; // why did I even open this. probably not stupid enough as a terrain choice for april fools
$SkiFreeTerrainListRejected[%k++] = "TWL-Abaddon.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-BeggarsRun.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Chokepoint.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Clusterfuct.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Desiccator.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Euro_Feign.ter"; // come on man
$SkiFreeTerrainListRejected[%k++] = "TWL-Frostclaw.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-Runenmacht.ter"; // nah
$SkiFreeTerrainListRejected[%k++] = "TWL-SubZero.ter";
$SkiFreeTerrainListRejected[%k++] = "UltimaThule.ter";
$SkiFreeTerrainListRejected[%k++] = "Underhill.ter";
$SkiFreeTerrainListRejected[%k++] = "WhiteDwarf.ter";
$SkiFreeTerrainListRejected[%k++] = "Whiteout.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_Birthright.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_Crown.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_DesertedSE.ter"; // This is a VERY jagged terrain.
$SkiFreeTerrainListRejected[%k++] = "Xtra_Voodoo.ter";
$SkiFreeTerrainListRejected[%k++] = "Xtra_Xerxes.ter";

// REJECTED FOR SOME OTHER REASON (14)
$SkiFreeTerrainListRejected[%k++] = "Chasmaclysmic.ter"; // this level is really kinda boring if it spawns right (which it can not do)
$SkiFreeTerrainListRejected[%k++] = "DMP_Pantheon.ter"; // there isn't enough value to this map to risk deadstopping
$SkiFreeTerrainListRejected[%k++] = "Lakefront.ter"; // just kinda hate this map tbh
$SkiFreeTerrainListRejected[%k++] = "Moonwalk.ter"; // magnum-like terrain
$SkiFreeTerrainListRejected[%k++] = "MyrkWood.ter"; // we don't need this when we have woodymyrk
$SkiFreeTerrainListRejected[%k++] = "Paranoia.ter"; // this map is basically flat garbage with a few hills to get in your way
$SkiFreeTerrainListRejected[%k++] = "Ramparts.ter"; // biased against copyright violation map
$SkiFreeTerrainListRejected[%k++] = "rst_agroleon.ter"; // the outer half of the terrain is too flat. and I deadstopped somewhere weird
$SkiFreeTerrainListRejected[%k++] = "rst_dermcity.ter"; // whatever the fuck this is doesn't seem good for this
$SkiFreeTerrainListRejected[%k++] = "TL_Magnum.ter"; // the best route is “discjump and keep landing on the flat parts at the top” – this is not compelling gameplay
$SkiFreeTerrainListRejected[%k++] = "Training5.ter"; // Terrain is WAY too dark and you can't tell features on it.
$SkiFreeTerrainListRejected[%k++] = "TWL-Drifts.ter"; // there's nothing really to this map outside the mission bounds
$SkiFreeTerrainListRejected[%k++] = "Xtra_AshenPowder.ter"; // can’t read that fucking terrain so i’m removing
$SkiFreeTerrainListRejected[%k++] = "Xtra_Helion.ter"; // this is just a really boring terrain

// DUPLICATES (15)
$SkiFreeTerrainListRejected[%k++] = "BeggarsRun.ter";
$SkiFreeTerrainListRejected[%k++] = "Damnation.ter";
$SkiFreeTerrainListRejected[%k++] = "Desiccator.ter"; // Things clearly seem to be at 4 plateaus of height. which doesn't make for good skiing.
$SkiFreeTerrainListRejected[%k++] = "DX_Badlands.ter";
$SkiFreeTerrainListRejected[%k++] = "DX_Desert.ter";
$SkiFreeTerrainListRejected[%k++] = "DX_Ice.ter";
$SkiFreeTerrainListRejected[%k++] = "Katabatic.ter";
$SkiFreeTerrainListRejected[%k++] = "Ravine.ter";
$SkiFreeTerrainListRejected[%k++] = "S5-Icedance.ter";
$SkiFreeTerrainListRejected[%k++] = "S5-massive.ter";
$SkiFreeTerrainListRejected[%k++] = "S5-Mordacity.ter";
$SkiFreeTerrainListRejected[%k++] = "Slapdash.ter";
$SkiFreeTerrainListRejected[%k++] = "SubZero.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-BlueMoon.ter";
$SkiFreeTerrainListRejected[%k++] = "TWL-DeadlyBirdsSong.ter"; // DBS_Smoothed.ter

$SkiFreeTerrainListMAX = %i;
$SkiFreeTerrainListSuperHardMAX = %j;
$SkiFreeTerrainListRejectedMAX = %k;
